###
POST http://localhost:3100/api/v1/categorias/new-ctg HTTP/1.1
Content-Type: application/json

{
    "nombre": "prueba2",
    "descripcion": "prueba.0"
}

###
GET http://localhost:3100/api/v1/categorias HTTP/1.1

###
GET http://localhost:3100/api/v1/categorias/6549c0d4a66ed10d09d92cdd HTTP/1.1

###
DELETE  http://localhost:3100/api/v1/categorias/654ab8b14dbcad779c033327 HTTP/1.1

///////////////////////////////////////////////////////////////////////////////////
###
POST http://localhost:3100/api/v1/productos/new-pro HTTP/1.1
Content-Type: application/json

{
    "nombre": "Ejemplo",
    "precio": 20300,
    "descuento": 5,
    "cantidad": 50,
    "disponibilidad": true,
    "categoriaId": "6547084a3136c6132ac65868"
}


###
GET http://localhost:3100/api/v1/productos/654709057475d38f59e2f7d7/productos HTTP/1.1

###
GET http://localhost:3100/api/v1/productos/6546d42ca4261fded22159e0 HTTP/1.1

###
GET http://localhost:3100/api/v1/productos HTTP/1.1

###
PATCH http://localhost:3100/api/v1/productos/6546d457a4261fded22159e3 HTTP/1.1
Content-Type: application/json

{
    "nombre": "Cambio",
    "precio": 27000,
    "descuento": 9,
    "cantidad": 76,
    "disponibilidad": true,
    "categoriaId": "6547084a3136c6132ac65868"
}

###
DELETE http://localhost:3100/api/v1/productos/6549c0e4a66ed10d09d92ce0 HTTP/1.1

###
POST http://localhost:3100/api/v1/auth/signin HTTP/1.1
Content-Type: application/json


{
    "nombre": "prueba",
    "apellido": "prueba",
    "email": "pepe123@",
    "telefono": "123456789",
    "contraseña": "123456789",
    "rol": "administrador"
}


###
GET http://localhost:3100/api/v1/categorias HTTP/1.1
Content-Type: application/json

###
DELETE http://localhost:3100/api/v1/categorias/65485e457607fd6fdda1d59b HTTP/1.1
Content-Type: application/json



###
POST http://localhost:3100/api/v1/suscripciones/new-suscription HTTP/1.1
Content-Type: application/json

{
    "nombre": "Lesmes",
    "correo": "correo@correo.com",
    "celular": "+573117752691"
}

###
GET http://localhost:3100/api/v1/suscripciones HTTP/1.1
Content-Type: application/json

###
DELETE http://localhost:3100/api/v1/suscripciones/6549946944fa75ead33d215d HTTP/1.1
Content-Type: application/json

###
GET http://localhost:3100/api/v1/usuarios HTTP/1.1

###
DELETE http://localhost:3100/api/v1/usuarios/654a4cee6d150b85eeceb75f HTTP/1.1
Content-Type: application/json

###
GET http://localhost:3100/api/v1/usuarios/email/camiangi1517@gmail.com HTTP/1.1
Content-Type: application/json